### ISSUE TITLE
MirageOS 3 beta package universe.

### ISSUE THREAD

**Issue by yomimono** [mirage/mirageos-3-beta#1]
With the last of the planned invasive changes to the MirageOS API completed, we're ready to assemble a set of libraries that will be used by MirageOS 3.  In other words, let's beta!

As discussed in our IRC meeting on 16 November 2016, here's the planned course of action:

For each repository with changes required for MirageOS 3, we'll:
  * update the CHANGELOG/CHANGES.md/other document that tracks changes
  * generate a new version number
  * generate a git tag with the new version number
  * generate a tarball representing that version of the software
  * make an entry in the packages/ directory of the mirageos-3-beta repository owned by mirage on GitHub for the package with the given version number, for each package built by that repository
  * fill the aforementioned per-package entries above with the corresponding `opam` and `url` files

For those repositories which have converted to `topkg`, these steps should be reasonably straightforward to automate and nearly the same as a normal release process -- the only difference is that a pull request should be made to `mirage/mirageos-3-beta` instead of `ocaml/opam-repository`.

Packages which are either referenced by the `mirage` front-end tool or are dependencies of some package referenced by the `mirage` front-end tool have versions already represented in this repository.  The repository will be updated with any additional point releases cut before the wider release into `opam-repository`.

-----

The following repositories are users or implementors of the sets of module types which are collected in the `mirage-types` and `mirage-types-lwt` packages.  They won't themselves work in the MirageOS 3 universe without an update.  They also won't be automatically included in unikernels without the user explicitly requesting them (via the ~packages argument to `foreign` in a config file).  Delay in including packages corresponding to these repositories *shouldn't* result in a broken universe, but users will be unable to build unikernels using these libraries in MirageOS 3 until new releases are cut.

I've tagged each with the first person(s) that came to mind to tag and release a MirageOS-3 compatible version of the packages in the repository.  If your repository appears below, you've probably already seen a few pull requests about compatibility with MirageOS 3.  If you don't wish to do this work or you're confused about what it entails, please feel free to respond here or privately.

Users and Implementors:
mirage/mirage-block-ramdisk (version 0.3 - minor increase) (moved from above - sorry @djs55)
mirage/ocaml-git (@samoht)
mirage/irmin (@samoht has large changes in progress here)
mirage/ocaml-9p (@djs55 @dsheets @talex5)
docker/datakit (@talex5)
sg2342/mirage-block-ccm (@sg2342)
gregtatcam/imaplet-lwt (@gregtatcam)
mirage/ocaml-qcow (@djs55)
mirage/ocaml-vhd (@djs55 @jonludlam)
mirage/ocaml-hvsock (@djs55)
mirage/shared-block-ring (@djs55 @jonludlam)
xapi-project/nbd (@jonludlam)
mirage/mirage-www (@avsm @amirmc @mor1 @yomimono, arbitrarily)
haesbaert/charrua-unix (@haesbaert)

There are a few repositories included in mirage-dev for which I think no direct work is required:
mirage/ocaml-github
inhabitedtype/ocaml-session

**Comment by yomimono** [comment]
I hope to have all packages above the line included in this repository by early next week.  If I've tagged you for something above the line (@hannesm @mato @pqwy) and this is unreasonable, please let me know.

**Comment by mato** [comment]
Regarding version numbers, all of the packages listed under my name are currently at `0.1.1`, so I'll just use `0.2.0` for all of the new releases.

I'm trying to use the following workflow to cut releases of those packages which use topkg to build (everything except solo5/solo5):

1. `topkg status`
2. `topkg log edit`, write up major changes from `status` output, bump version to 0.2.0.
3. `topkg log commit`
4. Manually check that `opam` metadata matches that from mirage/mirage-dev (@avsm added `org:mirage` for a bunch of packages yesterday). If not, update `opam` and commit.
4. `topkg tag`

So far, so good, except that:

* Should be doing this on a branch and then PR the package, or just push to `master` directly?
* Will we be using `git:` (pointing to a tag) or `archive:` style URLs for this OPAM repository? If the former then it's easy to manually create the `url` files, if the latter then how can I create them in an automated way? `topkg distrib` followed by `topkg opam pkg` provides some tooling for this but uses `bzip2` for the distribution files which is not the format that Github uses for release downloads...?

**Comment by mato** [comment]
Following up on the above, I see now that you mention generating tarballs so we will use `archive:` URLs in the `url` files. Do we have a tool in our menagerie that can automate the generation of these?

**Comment by samoht** [comment]
`topkg publish` will create the archive for you (and the GitHub release object with the changelog).

**Comment by yomimono** [comment]
After merging #6 I've removed the version annotations from the packages under my name above.  I believe each repository listed under my name is now represented by a tarball here, and the version numbers represented in the repository should be authoritative.

I've updated the README with some barebones instructions.

As of #1 - #6, most packages which are present are installing properly, with the exception of `mirage-entropy` which depends on `mirage-os-shim`.  I've contacted @pqwy and asked for releases of `mirage-os-shim`, `ocb-stubblr`, and the `ocaml-tls` and `nocrypto` libraries in the mirleft organization.  (@hannesm, perhaps you're already working on the latter two?)

@mato and @hannesm, thanks for your releases and PRs. :)

**Comment by hannesm** [comment]
@yomimono thx! nocrypto is @pqwy territory, and it doesn't make sense to release tls before nocrypto.  I'm happy to release tls once there is a nocrypto release.

**Comment by yomimono** [comment]
I've merged PRs for `mirage-os-shim`, `ocb-stubblr`, `nocrypto`, and `tls`.  Thanks @hannesm and @pqwy!

Unikernels which use any of the functions provided by the `Mirage` module should now be buildable if you have added the `mirageos-3-beta` remote.  Counterexamples welcome :) I'll post to `mirageos-devel` tomorrow announcing the readiness of the beta before our fortnightly meeting.

**Comment by mato** [comment]
@yomimono @pqwy I get the following error when installing `nocrypto` from this OPAM remote:
````
[ERROR] Bad checksum for
        /home/mato/.opam/packages.dev/nocrypto.0.5.4/nocrypto-0.5.4.tbz:
          - 31d0b0094178a95cd9b8892a159a6bfd [expected result]
          - c331a7a4d2a563d1d5ed581aeb849011 [actual result]
        This may be fixed by running `opam update`.
````

**Comment by mato** [comment]
Another thing I just noticed, the majority of packages in the repository do not have a `descr` file. Is that intentional?

**Comment by yomimono** [comment]
Intentionally lazy.  I thought briefly "is it worth it to pull `descr`s?" and thought "no" without much force; if anyone cares I'm happy to copy them in en masse.

**Comment by mato** [comment]
@yomimono If you don't mind copying the missing `descr`s in en masse for the sake of a nicer `opam list`, that'd be great!

**Comment by avsm** [comment]
To follow on from https://github.com/yomimono/charrua-client/pull/17, should we add more conflicts on `"mirage-types-lwt" < "3.0.0"` across the board, to prevent the old types ever trying to be used?

**Comment by yomimono** [comment]
Beta's closed, so this issue is too.
